package com.gti619.model;
// default package
// Generated Dec 4, 2016 7:41:08 PM by Hibernate Tools 5.1.0.Beta1

/**
 * MatriceUser generated by hbm2java
 */
public class MatriceUser implements java.io.Serializable {

	private Integer idmatriceUser;
	private User user;
	private String value;
	private Integer currentCheckSuccess;

	public MatriceUser() {
	}

	public MatriceUser(User user, String value, Integer currentCheckSuccess) {
		this.user = user;
		this.value = value;
		this.currentCheckSuccess = currentCheckSuccess;
	}

	public Integer getIdmatriceUser() {
		return this.idmatriceUser;
	}

	public void setIdmatriceUser(Integer idmatriceUser) {
		this.idmatriceUser = idmatriceUser;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Integer getCurrentCheckSuccess() {
		return this.currentCheckSuccess;
	}

	public void setCurrentCheckSuccess(Integer currentCheckSuccess) {
		this.currentCheckSuccess = currentCheckSuccess;
	}

}
