package com.gti619.model;
// default package
// Generated Nov 28, 2016 4:33:27 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * OldPassword generated by hbm2java
 */
public class OldPassword implements java.io.Serializable {

	private Integer idoldPass;
	private User user;
	private String oldPassword;
	private Date date;

	public OldPassword() {
	}

	public OldPassword(User user, String oldPassword, Date date) {
		this.user = user;
		this.oldPassword = oldPassword;
		this.date = date;
	}

	public Integer getIdoldPass() {
		return this.idoldPass;
	}

	public void setIdoldPass(Integer idoldPass) {
		this.idoldPass = idoldPass;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getOldPassword() {
		return this.oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
