package com.gti619.model;
// default package
// Generated Nov 28, 2016 4:33:27 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer idrole;
	private String nom;
	private Set users = new HashSet(0);

	public Role() {
	}

	public Role(String nom, Set users) {
		this.nom = nom;
		this.users = users;
	}

	public Integer getIdrole() {
		return this.idrole;
	}

	public void setIdrole(Integer idrole) {
		this.idrole = idrole;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
