package com.gti619.model;
// default package
// Generated Nov 28, 2016 4:33:27 PM by Hibernate Tools 5.1.0.Beta1

/**
 * SecurityConfig generated by hbm2java
 */
public class SecurityConfig implements java.io.Serializable {

	private Integer idconfig;
	private int nbTentativesMax;
	private Integer authenticationTimeout;
	private Integer nbOldPasswordToSave;
	private String hashFuncVersion;

	public SecurityConfig() {
	}

	public SecurityConfig(int nbTentativesMax) {
		this.nbTentativesMax = nbTentativesMax;
	}

	public SecurityConfig(int nbTentativesMax, Integer authenticationTimeout, Integer nbOldPasswordToSave,
			String hashFuncVersion) {
		this.nbTentativesMax = nbTentativesMax;
		this.authenticationTimeout = authenticationTimeout;
		this.nbOldPasswordToSave = nbOldPasswordToSave;
		this.hashFuncVersion = hashFuncVersion;
	}

	public Integer getIdconfig() {
		return this.idconfig;
	}

	public void setIdconfig(Integer idconfig) {
		this.idconfig = idconfig;
	}

	public int getNbTentativesMax() {
		return this.nbTentativesMax;
	}

	public void setNbTentativesMax(int nbTentativesMax) {
		this.nbTentativesMax = nbTentativesMax;
	}

	public Integer getAuthenticationTimeout() {
		return this.authenticationTimeout;
	}

	public void setAuthenticationTimeout(Integer authenticationTimeout) {
		this.authenticationTimeout = authenticationTimeout;
	}

	public Integer getNbOldPasswordToSave() {
		return this.nbOldPasswordToSave;
	}

	public void setNbOldPasswordToSave(Integer nbOldPasswordToSave) {
		this.nbOldPasswordToSave = nbOldPasswordToSave;
	}

	public String getHashFuncVersion() {
		return this.hashFuncVersion;
	}

	public void setHashFuncVersion(String hashFuncVersion) {
		this.hashFuncVersion = hashFuncVersion;
	}

}
