package com.gti619.model;
// default package
// Generated Dec 4, 2016 7:41:08 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer iduser;
	private Role role;
	private String email;
	private String mdp;
	private String name;
	private String login;
	private Integer isLocked;
	private String salt;
	private String recoveryId;
	private int nbTentativesConn;
	private Set oldPasswords = new HashSet(0);
	private Set matriceUsers = new HashSet(0);

	public User() {
	}

	public User(Role role, int nbTentativesConn) {
		this.role = role;
		this.nbTentativesConn = nbTentativesConn;
	}

	public User(Role role, String email, String mdp, String name, String login, Integer isLocked, String salt,
			String recoveryId, int nbTentativesConn, Set oldPasswords, Set matriceUsers) {
		this.role = role;
		this.email = email;
		this.mdp = mdp;
		this.name = name;
		this.login = login;
		this.isLocked = isLocked;
		this.salt = salt;
		this.recoveryId = recoveryId;
		this.nbTentativesConn = nbTentativesConn;
		this.oldPasswords = oldPasswords;
		this.matriceUsers = matriceUsers;
	}

	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public Integer getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Integer isLocked) {
		this.isLocked = isLocked;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getRecoveryId() {
		return this.recoveryId;
	}

	public void setRecoveryId(String recoveryId) {
		this.recoveryId = recoveryId;
	}

	public int getNbTentativesConn() {
		return this.nbTentativesConn;
	}

	public void setNbTentativesConn(int nbTentativesConn) {
		this.nbTentativesConn = nbTentativesConn;
	}

	public Set getOldPasswords() {
		return this.oldPasswords;
	}

	public void setOldPasswords(Set oldPasswords) {
		this.oldPasswords = oldPasswords;
	}

	public Set getMatriceUsers() {
		return this.matriceUsers;
	}

	public void setMatriceUsers(Set matriceUsers) {
		this.matriceUsers = matriceUsers;
	}

}
