package com.gti619.model;
// default package
// Generated Nov 28, 2016 1:56:39 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer iduser;
	private Role role;
	private String email;
	private String mdp;
	private String name;
	private String FName;
	private Boolean isLocked;
	private String salt;
	private Set oldPasswords = new HashSet(0);

	public User() {
	}

	public User(Role role) {
		this.role = role;
	}

	public User(Role role, String email, String mdp, String name, String FName, Boolean isLocked, String salt,
			Set oldPasswords) {
		this.role = role;
		this.email = email;
		this.mdp = mdp;
		this.name = name;
		this.FName = FName;
		this.isLocked = isLocked;
		this.salt = salt;
		this.oldPasswords = oldPasswords;
	}

	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public Boolean getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public Set getOldPasswords() {
		return this.oldPasswords;
	}

	public void setOldPasswords(Set oldPasswords) {
		this.oldPasswords = oldPasswords;
	}

}
